POST  http://localhost:3000/register
Content-Type: application/json

 {
    "userName":"SolGen",
    "name": "Bien",
    "email":"solGeneration@youtu.be",
    "password":"sdfhUHUbvy"
 }

####
POST  http://localhost:3000/login
Content-Type: application/json

 {
    "email":"yourguyscow@youtu.be",
    "password":"dCWLVppbYRC1"
 } 

###
POST  http://localhost:3000/updateProfile
Content-Type: application/json

 {
    "userName": "Teebaeg",
    "Name": "Love",
    "email":"yourguyscow@youtu.be"
 } 