POST  http://localhost:5005/register
Content-Type: application/json

 {
    "userName":"triston",
    "Name": "badboy",
    "email":"badboytriston@gmail.com",
    "password":"tristin"
 }

####
POST  http://localhost:3000/login
Content-Type: application/json

 {
    "email":"badboytriston@gmail.com",
    "password":"tristin"
 } 

###
POST  http://localhost:3000/updateProfile
Content-Type: application/json

 {
    "userName": "Teebaeg",
    "Name": "Love",
    "email":"yourguyscow@youtu.be"
 } 