GET http://localhost:5000/search/?query=cup
Content-Type: application/json


###
POST http://localhost:5000/checkout
Content-Type: application/json

{
    "UserId": 5,
    "quantity":  1,
    "total": 140,
    "ProductId":  [3, 7]
}
####

POST http://localhost:5000/setAdmin
Content-Type: application/json

{
    "email":"testuser6@gmail.com", 
    "userID": 14
}

####

POST http://localhost:5000/allProducts
Content-Type: application/json

{
    "pageNumber":1,
    "rowNumber":5
}

###
GET http://localhost:5000/product/4
