###
POST http://localhost:5000/search
Content-Type: application/json

{
    "Search": "Cup"
}

###
POST http://localhost:5000/checkout
Content-Type: application/json

{
    "UserId": 5,
    "quantity":  1,
    "total": 140,
    "ProductId":  [3, 7]
}
####

POST http://localhost:5000/setAdmin
Content-Type: application/json

{
    "userID": 1,
    "role":"User"
}

####

POST http://localhost:5000/allProducts
Content-Type: application/json

{
    "pageNumber":1,
    "rowNumber":5
}

###
GET http://localhost:5000/product/4
#####

POST http://localhost:5000/addProduct
Content-Type: application/json

{
   "categoryName":"Bedroom",
   "productName":"mirror",
   "productDesc":"Best mirror in town",
   "productImg":"http://blog.aspneter.com/Images/no-thumb.jpg",
   "productPrice":"1399",
   "quantity":"40"
}
####
GET http://localhost:5000/adminProducts

####
POST http://localhost:5000/updateProduct
Content-Type: application/json

{
   "id":"2",
   "name":"book",
   "desc":"changed description",
   "price":23,
   "quantity":40,
   "discount":12 
}

#####

GET http://localhost:5000/getOneProduct/4

#####
POST http://localhost:5000/deleteProduct
Content-Type: application/json

{
    "id":5
}
